Repository albin-johansson/TDA367-OOP-Project, pull requests merged in 2019-10, with the labels that each got.

#82 Separate canvas from root 78
  src/main/java/chalmers/pimp/controller/components/CanvasPane.java
  src/main/java/chalmers/pimp/controller/components/PimpEditorPane.java
  src/main/resources/canvas_pane.fxml
  src/main/resources/root.fxml
Labels: enhancement

#85 Eraser tool 80
  src/main/java/chalmers/pimp/controller/ControllerImpl.java
  src/main/java/chalmers/pimp/controller/IController.java
  src/main/java/chalmers/pimp/model/IRenderer.java
  src/main/java/chalmers/pimp/model/tools/Pencil.java
  src/main/java/chalmers/pimp/view/ViewImpl.java
  src/main/java/chalmers/pimp/view/renderer/FXRenderer.java
Labels: enhancement

#91 Move tool 87
  src/main/java/chalmers/pimp/controller/ControllerImpl.java
  src/main/java/chalmers/pimp/controller/IController.java
  src/main/java/chalmers/pimp/controller/components/PalettePane.java
  src/main/java/chalmers/pimp/model/IModel.java
  src/main/java/chalmers/pimp/model/ModelImpl.java
  src/main/java/chalmers/pimp/model/canvas/Canvas.java
  src/main/java/chalmers/pimp/model/tools/MoveTool.java
  src/main/java/chalmers/pimp/model/tools/ToolFactory.java
  src/main/resources/images/dark/move.png
  src/main/resources/images/light/move.png
  src/main/resources/palette_pane.fxml
  src/test/java/chalmers/pimp/model/ModelImplTest.java
Labels: enhancement

#93 File import/89
  src/main/java/chalmers/pimp/controller/ControllerImpl.java
  src/main/java/chalmers/pimp/controller/IController.java
  src/main/java/chalmers/pimp/controller/components/ImageChooser.java
  src/main/java/chalmers/pimp/controller/components/ToolbarPane.java
  src/main/java/chalmers/pimp/model/canvas/layer/LayerFactory.java
  src/main/java/chalmers/pimp/model/canvas/layer/Raster.java
  src/main/java/chalmers/pimp/model/canvas/layer/Rectangle.java
  src/main/java/chalmers/pimp/model/pixeldata/PixelData.java
  src/main/java/chalmers/pimp/model/pixeldata/PixelFactory.java
  src/main/java/chalmers/pimp/service/FXToPixelDataService.java
  src/main/java/chalmers/pimp/service/ImageImportService.java
  src/main/resources/images/dark/open_folder.png
  src/main/resources/images/light/open_folder.png
  src/main/resources/toolbar.fxml
  src/test/java/chalmers/pimp/model/canvas/CanvasTest.java
  src/test/java/chalmers/pimp/model/pixeldata/PixelFactoryTest.java
Labels: enhancement

#94 Add command pattern 86
  src/main/java/chalmers/pimp/controller/ControllerImpl.java
  src/main/java/chalmers/pimp/controller/IController.java
  src/main/java/chalmers/pimp/controller/components/PimpEditorPane.java
  src/main/java/chalmers/pimp/controller/components/ToolbarPane.java
  src/main/java/chalmers/pimp/model/AbstractComposite.java
  src/main/java/chalmers/pimp/model/IChangeable.java
  src/main/java/chalmers/pimp/model/ICopiable.java
  src/main/java/chalmers/pimp/model/IModel.java
  src/main/java/chalmers/pimp/model/IUndoRedoListener.java
  src/main/java/chalmers/pimp/model/ModelImpl.java
  src/main/java/chalmers/pimp/model/ModelMemento.java
  src/main/java/chalmers/pimp/model/Stroke.java
  src/main/java/chalmers/pimp/model/UndoRedoEvent.java
  src/main/java/chalmers/pimp/model/UndoRedoListenerComposite.java
  src/main/java/chalmers/pimp/model/canvas/Canvas.java
  src/main/java/chalmers/pimp/model/canvas/CanvasUpdateListenerComposite.java
  src/main/java/chalmers/pimp/model/canvas/LayerUpdateListenerComposite.java
  src/main/java/chalmers/pimp/model/canvas/layer/ILayer.java
  src/main/java/chalmers/pimp/model/canvas/layer/IReadOnlyLayer.java
  src/main/java/chalmers/pimp/model/canvas/layer/Raster.java
  src/main/java/chalmers/pimp/model/canvas/layer/Rectangle.java
  src/main/java/chalmers/pimp/model/color/ColorFactory.java
  src/main/java/chalmers/pimp/model/command/CommandFactory.java
  src/main/java/chalmers/pimp/model/command/CommandManager.java
  src/main/java/chalmers/pimp/model/command/ICommand.java
  src/main/java/chalmers/pimp/model/command/StrokeCommand.java
  src/main/java/chalmers/pimp/model/command/package-info.java
  src/main/java/chalmers/pimp/model/pixeldata/PixelFactory.java
  src/main/java/chalmers/pimp/model/pixeldata/PixelImpl.java
  src/main/java/chalmers/pimp/model/tools/Pencil.java
  src/main/java/chalmers/pimp/model/tools/ShapeTool.java
  src/main/java/chalmers/pimp/model/tools/ToolFactory.java
  src/main/java/chalmers/pimp/view/ViewImpl.java
  src/main/resources/styling/stylesheet.css
  src/main/resources/toolbar.fxml
  src/test/java/chalmers/pimp/model/ModelImplTest.java
  src/test/java/chalmers/pimp/model/ModelMementoTest.java
  src/test/java/chalmers/pimp/model/StrokeTest.java
  src/test/java/chalmers/pimp/model/UndoRedoEventTest.java
  src/test/java/chalmers/pimp/model/canvas/CanvasUpdateListenerCompositeTest.java
  src/test/java/chalmers/pimp/model/canvas/LayerUpdateListenerCompositeTest.java
  src/test/java/chalmers/pimp/model/command/CommandFactoryTest.java
  src/test/java/chalmers/pimp/model/command/CommandManagerTest.java
  src/test/java/chalmers/pimp/model/command/MockCommand.java
  src/test/java/chalmers/pimp/model/pixeldata/PixelFactoryTest.java
  src/test/java/chalmers/pimp/model/pixeldata/PixelImplTest.java
Labels: enhancement

#97 Fixed bug in setPixels
  src/main/java/chalmers/pimp/model/canvas/Canvas.java
Labels: bug

#92 Visual layer feedback#73, Moving layers #74 and Switching ActiveLayer #88
  src/main/java/chalmers/pimp/PimpApp.java
  src/main/java/chalmers/pimp/controller/ControllerFactory.java
  src/main/java/chalmers/pimp/controller/ControllerImpl.java
  src/main/java/chalmers/pimp/controller/IController.java
  src/main/java/chalmers/pimp/controller/components/LayerItemManagerPane.java
  src/main/java/chalmers/pimp/controller/components/LayerItemPane.java
  src/main/java/chalmers/pimp/controller/components/PalettePane.java
  src/main/java/chalmers/pimp/controller/components/PimpEditorPane.java
  src/main/java/chalmers/pimp/controller/components/ToolbarPane.java
  src/main/java/chalmers/pimp/controller/package-info.java
  src/main/java/chalmers/pimp/model/IModel.java
  src/main/java/chalmers/pimp/model/ModelImpl.java
  src/main/java/chalmers/pimp/model/canvas/Canvas.java
  src/main/java/chalmers/pimp/model/canvas/layer/ILayer.java
  src/main/java/chalmers/pimp/model/canvas/layer/IReadOnlyLayer.java
  src/main/java/chalmers/pimp/model/canvas/layer/LayerDelegate.java
  src/main/java/chalmers/pimp/model/canvas/layer/LayerUpdateEvent.java
  src/main/java/chalmers/pimp/model/canvas/layer/Raster.java
  src/main/java/chalmers/pimp/model/canvas/layer/Rectangle.java
  src/main/java/chalmers/pimp/model/package-info.java
  src/main/java/chalmers/pimp/model/tools/ITool.java
  src/main/java/chalmers/pimp/model/tools/ToolFactory.java
  src/main/java/chalmers/pimp/view/package-info.java
  src/main/resources/layer_item.fxml
  src/main/resources/layer_pane.fxml
  src/main/resources/toolbar.fxml
  src/test/java/chalmers/pimp/controller/ControllerImplTest.java
  src/test/java/chalmers/pimp/model/ModelImplTest.java
  src/test/java/chalmers/pimp/model/canvas/CanvasTest.java
  src/test/java/chalmers/pimp/model/canvas/layer/RasterTest.java
  src/test/java/chalmers/pimp/model/canvas/layer/RectangleTest.java
  src/test/java/chalmers/pimp/model/pixeldata/PixelDataTest.java
  src/test/java/chalmers/pimp/model/tools/PencilTest.java
  src/test/java/chalmers/pimp/util/AnchorPanesTest.java
Labels: enhancement

#101 Created a shape tool (only rectangles so far)
  src/main/java/chalmers/pimp/controller/ControllerImpl.java
  src/main/java/chalmers/pimp/controller/IController.java
  src/main/java/chalmers/pimp/controller/components/PalettePane.java
  src/main/java/chalmers/pimp/model/IModel.java
  src/main/java/chalmers/pimp/model/ModelImpl.java
  src/main/java/chalmers/pimp/model/canvas/Canvas.java
  src/main/java/chalmers/pimp/model/canvas/layer/LayerDelegate.java
  src/main/java/chalmers/pimp/model/canvas/layer/Raster.java
  src/main/java/chalmers/pimp/model/canvas/layer/Rectangle.java
  src/main/java/chalmers/pimp/model/color/ColorFactory.java
  src/main/java/chalmers/pimp/model/point/IPoint.java
  src/main/java/chalmers/pimp/model/point/IReadOnlyPoint.java
  src/main/java/chalmers/pimp/model/point/Point.java
  src/main/java/chalmers/pimp/model/point/PointFactory.java
  src/main/java/chalmers/pimp/model/tools/ShapeTool.java
  src/main/java/chalmers/pimp/model/tools/ToolFactory.java
  src/main/java/chalmers/pimp/view/IView.java
  src/main/java/chalmers/pimp/view/ViewImpl.java
  src/main/resources/images/dark/rectangle.png
  src/main/resources/images/light/rectangle.png
  src/main/resources/palette_pane.fxml
Labels: enhancement, good first issue

#104 Gui improvements 100
  src/main/java/chalmers/pimp/PimpApp.java
  src/main/java/chalmers/pimp/controller/components/LayerItemManagerPane.java
  src/main/java/chalmers/pimp/controller/components/LayerItemPane.java
  src/main/java/chalmers/pimp/model/IModel.java
  src/main/java/chalmers/pimp/model/ModelImpl.java
  src/main/java/chalmers/pimp/model/canvas/Canvas.java
  src/main/resources/images/dark/arrow_down.png
  src/main/resources/images/dark/arrow_up.png
  src/main/resources/images/dark/pixels.png
  src/main/resources/images/dark/raster.png
  src/main/resources/images/dark/shape.png
  src/main/resources/images/dark/trash.png
  src/main/resources/images/light/arrow_down.png
  src/main/resources/images/light/arrow_up.png
  src/main/resources/images/light/pixels.png
  src/main/resources/images/light/raster.png
  src/main/resources/images/light/shape.png
  src/main/resources/images/light/trash.png
  src/main/resources/layer_item.fxml
  src/main/resources/layer_pane.fxml
  src/main/resources/styling/stylesheet.css
Labels: enhancement

#107 Removed redundant method and replace with service
  src/main/java/chalmers/pimp/view/renderer/FXRenderer.java
Labels: bug, good first issue

#108 Added Enum value for MouseButton in MoseStatus
  src/main/java/chalmers/pimp/controller/ControllerImpl.java
  src/main/java/chalmers/pimp/model/MouseStatus.java
  src/main/java/chalmers/pimp/service/FXToMouseStatusButtonService.java
  src/test/java/chalmers/pimp/model/MouseStatusTest.java
Labels: enhancement

#112 Drag and drop layers 109
  src/main/java/chalmers/pimp/controller/components/LayerItemPane.java
  src/main/resources/layer_item.fxml
  src/main/resources/styling/stylesheet.css
Labels: enhancement

#116 Oscaralmstrom patch 1
  README.md
Labels: documentation

#115 Add bottom panel 114
  src/main/java/chalmers/pimp/controller/ControllerImpl.java
  src/main/java/chalmers/pimp/controller/components/CanvasPane.java
  src/main/java/chalmers/pimp/controller/components/InfoPane.java
  src/main/java/chalmers/pimp/controller/components/PimpEditorPane.java
  src/main/resources/info_pane.fxml
  src/main/resources/root.fxml
  src/main/resources/styling/stylesheet.css
  src/main/resources/toolbar.fxml
Labels: enhancement

#118 Imported image name
  src/main/java/chalmers/pimp/controller/ControllerImpl.java
  src/main/java/chalmers/pimp/controller/components/ImageChooser.java
  src/main/java/chalmers/pimp/model/canvas/layer/LayerFactory.java
  src/main/java/chalmers/pimp/model/canvas/layer/Raster.java
  src/main/java/chalmers/pimp/service/FileService.java
Labels: enhancement

#119 Doodle2/96
  src/main/java/chalmers/pimp/controller/ControllerImpl.java
  src/main/java/chalmers/pimp/controller/IController.java
  src/main/java/chalmers/pimp/controller/components/PalettePane.java
  src/main/java/chalmers/pimp/controller/components/PimpEditorPane.java
  src/main/java/chalmers/pimp/model/IRenderer.java
  src/main/java/chalmers/pimp/model/canvas/layer/Doodle.java
  src/main/java/chalmers/pimp/model/canvas/layer/IReadOnlyLayer.java
  src/main/java/chalmers/pimp/model/canvas/layer/LayerFactory.java
  src/main/java/chalmers/pimp/model/canvas/layer/LayerType.java
  src/main/java/chalmers/pimp/model/canvas/layer/Raster.java
  src/main/java/chalmers/pimp/model/canvas/layer/Rectangle.java
  src/main/java/chalmers/pimp/model/tools/DoodleTool.java
  src/main/java/chalmers/pimp/model/tools/ToolFactory.java
  src/main/java/chalmers/pimp/view/renderer/FXRenderer.java
  src/main/resources/palette_pane.fxml
  src/test/java/chalmers/pimp/model/canvas/layer/DoodleTest.java
  src/test/java/chalmers/pimp/model/mock/Line.java
  src/test/java/chalmers/pimp/model/mock/RendererMock.java
Labels: enhancement

#122 Updated InfoPane class with javadoc, added styling to context menu
  src/main/java/chalmers/pimp/controller/components/InfoPane.java
  src/main/java/chalmers/pimp/controller/components/PimpEditorPane.java
  src/main/resources/styling/stylesheet.css
Labels: documentation

#135 Add color picker
  src/main/java/chalmers/pimp/PimpApp.java
  src/main/java/chalmers/pimp/controller/ControllerImpl.java
  src/main/java/chalmers/pimp/controller/components/ColorPickerPane.java
  src/main/java/chalmers/pimp/controller/components/PimpEditorPane.java
  src/main/java/chalmers/pimp/controller/components/UtilityPane.java
  src/main/java/chalmers/pimp/model/IModel.java
  src/main/java/chalmers/pimp/model/IRenderer.java
  src/main/java/chalmers/pimp/model/ModelImpl.java
  src/main/java/chalmers/pimp/model/ModelMemento.java
  src/main/java/chalmers/pimp/model/Stroke.java
  src/main/java/chalmers/pimp/model/canvas/layer/Doodle.java
  src/main/java/chalmers/pimp/model/canvas/layer/LayerFactory.java
  src/main/java/chalmers/pimp/model/canvas/layer/Rectangle.java
  src/main/java/chalmers/pimp/model/color/ColorFactory.java
  src/main/java/chalmers/pimp/model/color/ColorImpl.java
  src/main/java/chalmers/pimp/model/color/Colors.java
  src/main/java/chalmers/pimp/model/color/IColor.java
  src/main/java/chalmers/pimp/model/color/IReadOnlyColor.java
  src/main/java/chalmers/pimp/model/color/colormodel/ColorModelFactory.java
  src/main/java/chalmers/pimp/model/color/colormodel/ColorModelImpl.java
  src/main/java/chalmers/pimp/model/color/colormodel/ColorModelMemento.java
  src/main/java/chalmers/pimp/model/color/colormodel/IColorChangeListener.java
  src/main/java/chalmers/pimp/model/color/colormodel/IColorChangeObservable.java
  src/main/java/chalmers/pimp/model/color/colormodel/IColorModel.java
  src/main/java/chalmers/pimp/model/command/ChangeColorCommand.java
  src/main/java/chalmers/pimp/model/command/CommandFactory.java
  src/main/java/chalmers/pimp/model/command/StrokeCommand.java
  src/main/java/chalmers/pimp/model/pixeldata/IReadOnlyPixel.java
  src/main/java/chalmers/pimp/model/pixeldata/PixelFactory.java
  src/main/java/chalmers/pimp/model/pixeldata/PixelImpl.java
  src/main/java/chalmers/pimp/model/tools/DoodleTool.java
  src/main/java/chalmers/pimp/model/tools/ShapeTool.java
  src/main/java/chalmers/pimp/model/tools/ToolFactory.java
  src/main/java/chalmers/pimp/service/ColorConverterService.java
  src/main/java/chalmers/pimp/util/AnchorPanes.java
  src/main/java/chalmers/pimp/view/renderer/FXRenderer.java
  src/main/resources/color_picker.fxml
  src/main/resources/layer_pane.fxml
  src/main/resources/root.fxml
  src/main/resources/styling/stylesheet.css
  src/main/resources/utility_pane.fxml
  src/test/java/chalmers/pimp/model/ModelMementoTest.java
  src/test/java/chalmers/pimp/model/StrokeTest.java
  src/test/java/chalmers/pimp/model/canvas/layer/DoodleTest.java
  src/test/java/chalmers/pimp/model/canvas/layer/RectangleTest.java
  src/test/java/chalmers/pimp/model/color/ColorImplTest.java
  src/test/java/chalmers/pimp/model/mock/RendererMock.java
  src/test/java/chalmers/pimp/model/pixeldata/PixelFactoryTest.java
Labels: enhancement

#141 Color picker improvements
  src/main/java/chalmers/pimp/controller/components/ColorPickerPane.java
  src/main/java/chalmers/pimp/controller/components/UtilityPane.java
  src/main/java/chalmers/pimp/model/color/IColor.java
Labels: bug

#142 Import images correctly. Was imported as a transparent image
  src/main/java/chalmers/pimp/model/IRenderer.java
  src/main/java/chalmers/pimp/model/canvas/layer/Raster.java
  src/main/java/chalmers/pimp/service/FXToPixelDataService.java
  src/main/java/chalmers/pimp/view/renderer/FXRenderer.java
  src/test/java/chalmers/pimp/model/mock/RendererMock.java
Labels: bug

#136 RotateTool created which rotates most Layers correctly
  src/main/java/chalmers/pimp/controller/ControllerImpl.java
  src/main/java/chalmers/pimp/controller/IController.java
  src/main/java/chalmers/pimp/controller/components/PalettePane.java
  src/main/java/chalmers/pimp/model/IModel.java
  src/main/java/chalmers/pimp/model/IRenderer.java
  src/main/java/chalmers/pimp/model/LayerRotation.java
  src/main/java/chalmers/pimp/model/ModelImpl.java
  src/main/java/chalmers/pimp/model/Point.java
  src/main/java/chalmers/pimp/model/canvas/CanvasImpl.java
  src/main/java/chalmers/pimp/model/canvas/ICanvas.java
  src/main/java/chalmers/pimp/model/canvas/LayerManager.java
  src/main/java/chalmers/pimp/model/canvas/layer/Doodle.java
  src/main/java/chalmers/pimp/model/canvas/layer/ILayer.java
  src/main/java/chalmers/pimp/model/canvas/layer/IReadOnlyLayer.java
  src/main/java/chalmers/pimp/model/canvas/layer/LayerDelegate.java
  src/main/java/chalmers/pimp/model/canvas/layer/Raster.java
  src/main/java/chalmers/pimp/model/canvas/layer/Rectangle.java
  src/main/java/chalmers/pimp/model/command/CommandFactory.java
  src/main/java/chalmers/pimp/model/command/MoveCommand.java
  src/main/java/chalmers/pimp/model/command/RotateCommand.java
  src/main/java/chalmers/pimp/model/tools/RotateTool.java
  src/main/java/chalmers/pimp/model/tools/ToolFactory.java
  src/main/java/chalmers/pimp/view/ViewImpl.java
  src/main/java/chalmers/pimp/view/renderer/FXRenderer.java
  src/main/resources/images/dark/rotate.png
  src/main/resources/images/light/rotate.png
  src/main/resources/palette_pane.fxml
  src/main/resources/styling/stylesheet.css
  src/test/java/chalmers/pimp/model/LayerRotationTest.java
  src/test/java/chalmers/pimp/model/canvas/layer/DoodleTest.java
  src/test/java/chalmers/pimp/model/command/CommandFactoryTest.java
  src/test/java/chalmers/pimp/model/mock/Line.java
  src/test/java/chalmers/pimp/model/mock/RendererMock.java
Labels: enhancement

#140 Fixed getHeight and getWidth
  .travis.yml
  README.md
  src/main/java/chalmers/pimp/model/canvas/layer/Doodle.java
  src/main/java/chalmers/pimp/model/tools/DoodleTool.java
Labels: bug

#143 Rotation fix
  src/main/java/chalmers/pimp/model/canvas/layer/Doodle.java
  src/main/java/chalmers/pimp/model/canvas/layer/Raster.java
  src/main/java/chalmers/pimp/model/canvas/layer/Rectangle.java
Labels: bug

#144 Layer preview 120
  src/main/java/chalmers/pimp/controller/components/LayerItemContainerPane.java
  src/main/java/chalmers/pimp/controller/components/LayerItemPane.java
  src/main/java/chalmers/pimp/model/ModelImpl.java
  src/main/java/chalmers/pimp/service/LayerImageService.java
  src/main/resources/images/dark/checkmark.png
  src/main/resources/images/light/checkmark.png
  src/main/resources/layer_item.fxml
  src/main/resources/styling/stylesheet.css
Labels: enhancement

#146 Doodle should now rotate right
  src/main/java/chalmers/pimp/model/canvas/layer/Doodle.java
Labels: enhancement

#147 When setting doodle x/y the getter for x/y will retrun the same result
  src/main/java/chalmers/pimp/model/canvas/layer/Doodle.java
  src/test/java/chalmers/pimp/model/canvas/layer/DoodleTest.java
Labels: bug

#148 Disable unavailable tools
  src/main/java/chalmers/pimp/controller/components/PalettePane.java
  src/main/java/chalmers/pimp/controller/components/PimpEditorPane.java
  src/main/resources/palette_pane.fxml
Labels: enhancement

#150 reversed boolean statements in enableRasterTools
  src/main/java/chalmers/pimp/controller/components/PalettePane.java
Labels: bug

#154 Redraw layer preview when changing a layer's color
  src/main/java/chalmers/pimp/model/canvas/LayerManager.java
Labels: bug

#151 Split ilayer/131
  src/main/java/chalmers/pimp/model/Point.java
  src/main/java/chalmers/pimp/model/canvas/LayerManager.java
  src/main/java/chalmers/pimp/model/canvas/layer/Doodle.java
  src/main/java/chalmers/pimp/model/canvas/layer/IDoodleLayer.java
  src/main/java/chalmers/pimp/model/canvas/layer/ILayer.java
  src/main/java/chalmers/pimp/model/canvas/layer/IRasterLayer.java
  src/main/java/chalmers/pimp/model/canvas/layer/LayerFactory.java
  src/main/java/chalmers/pimp/model/canvas/layer/Raster.java
  src/main/java/chalmers/pimp/model/canvas/layer/Rectangle.java
  src/main/java/chalmers/pimp/model/tools/DoodleTool.java
  src/test/java/chalmers/pimp/model/canvas/layer/DoodleTest.java
  src/test/java/chalmers/pimp/model/canvas/layer/RasterTest.java
  src/test/java/chalmers/pimp/model/canvas/layer/RectangleTest.java
Labels: enhancement

#155 Abstract command separation
  src/main/java/chalmers/pimp/model/ModelImpl.java
  src/main/java/chalmers/pimp/model/command/AbstractCommand.java
  src/main/java/chalmers/pimp/model/command/AddLayerCommand.java
  src/main/java/chalmers/pimp/model/command/ChangeColorCommand.java
  src/main/java/chalmers/pimp/model/command/ChangeLayerDepthCommand.java
  src/main/java/chalmers/pimp/model/command/CommandFactory.java
  src/main/java/chalmers/pimp/model/command/LayerSelectionCommand.java
  src/main/java/chalmers/pimp/model/command/MoveCommand.java
  src/main/java/chalmers/pimp/model/command/RemoveLayerCommand.java
  src/main/java/chalmers/pimp/model/command/RotateCommand.java
  src/main/java/chalmers/pimp/model/command/StrokeCommand.java
Labels: enhancement

#156 Encapsulate PixelData and improve raster data services
  src/main/java/chalmers/pimp/controller/ControllerImpl.java
  src/main/java/chalmers/pimp/controller/components/ImageChooser.java
  src/main/java/chalmers/pimp/model/IRenderer.java
  src/main/java/chalmers/pimp/model/Stroke.java
  src/main/java/chalmers/pimp/model/canvas/CanvasImpl.java
  src/main/java/chalmers/pimp/model/canvas/ICanvas.java
  src/main/java/chalmers/pimp/model/canvas/LayerManager.java
  src/main/java/chalmers/pimp/model/canvas/layer/Doodle.java
  src/main/java/chalmers/pimp/model/canvas/layer/IReadOnlyLayer.java
  src/main/java/chalmers/pimp/model/canvas/layer/LayerFactory.java
  src/main/java/chalmers/pimp/model/canvas/layer/Raster.java
  src/main/java/chalmers/pimp/model/canvas/layer/Rectangle.java
  src/main/java/chalmers/pimp/model/pixeldata/IRasterData.java
  src/main/java/chalmers/pimp/model/pixeldata/IReadOnlyRasterData.java
  src/main/java/chalmers/pimp/model/pixeldata/RasterDataFactory.java
  src/main/java/chalmers/pimp/model/pixeldata/RasterDataImpl.java
  src/main/java/chalmers/pimp/service/FXToPixelDataService.java
  src/main/java/chalmers/pimp/service/PixelDataToFXService.java
  src/main/java/chalmers/pimp/service/RasterDataService.java
  src/main/java/chalmers/pimp/service/package-info.java
  src/main/java/chalmers/pimp/view/renderer/FXRenderer.java
  src/main/java/chalmers/pimp/view/renderer/SwingRenderer.java
  src/test/java/chalmers/pimp/model/mock/RendererMock.java
  src/test/java/chalmers/pimp/model/pixeldata/PixelDataTest.java
  src/test/java/chalmers/pimp/model/pixeldata/RasterDataImplTest.java
Labels: enhancement

#157 Functional decomposition and javadoc
  src/main/java/chalmers/pimp/controller/components/LayerItemContainerPane.java
  src/main/java/chalmers/pimp/controller/components/LayerItemPane.java
  src/main/java/chalmers/pimp/model/IModel.java
  src/main/java/chalmers/pimp/model/ModelImpl.java
  src/main/java/chalmers/pimp/model/canvas/CanvasImpl.java
  src/main/java/chalmers/pimp/model/canvas/ICanvas.java
  src/main/java/chalmers/pimp/model/canvas/LayerManager.java
  src/main/java/chalmers/pimp/model/canvas/LayerUpdateListenerComposite.java
  src/main/java/chalmers/pimp/model/canvas/layer/Doodle.java
  src/main/java/chalmers/pimp/model/canvas/layer/ILayer.java
  src/main/java/chalmers/pimp/model/canvas/layer/ILayerUpdateListener.java
  src/main/java/chalmers/pimp/model/canvas/layer/IRasterLayer.java
  src/main/java/chalmers/pimp/model/canvas/layer/IReadOnlyLayer.java
  src/main/java/chalmers/pimp/model/canvas/layer/Raster.java
  src/main/java/chalmers/pimp/model/canvas/layer/Rectangle.java
  src/main/java/chalmers/pimp/model/color/colormodel/IColorModel.java
  src/main/resources/layer_pane.fxml
  src/main/resources/styling/stylesheet.css
  src/test/java/chalmers/pimp/model/ModelImplTest.java
  src/test/java/chalmers/pimp/model/canvas/CanvasImplTest.java
  src/test/java/chalmers/pimp/model/canvas/LayerManagerTest.java
  src/test/java/chalmers/pimp/model/canvas/LayerUpdateListenerCompositeTest.java
  src/test/java/chalmers/pimp/model/canvas/layer/RasterTest.java
  src/test/java/chalmers/pimp/model/canvas/layer/RectangleTest.java
Labels: enhancement

#158 Updated the raster pen icon and updated the dividers color
  src/main/java/chalmers/pimp/model/color/ColorFactory.java
  src/main/java/chalmers/pimp/model/color/ColorImpl.java
  src/main/java/chalmers/pimp/model/color/IColor.java
  src/main/java/chalmers/pimp/service/ColorConverterService.java
  src/main/resources/images/dark/pixels.png
  src/main/resources/images/dark/raster_pen.png
  src/main/resources/images/light/pixels.png
  src/main/resources/images/light/raster_pen.png
  src/main/resources/palette_pane.fxml
  src/main/resources/styling/stylesheet.css
Labels: enhancement

#160 Improve testing
  src/main/java/chalmers/pimp/controller/components/ImageChooser.java
  src/main/java/chalmers/pimp/model/IModel.java
  src/main/java/chalmers/pimp/model/IRenderer.java
  src/main/java/chalmers/pimp/model/ModelImpl.java
  src/main/java/chalmers/pimp/model/canvas/LayerManager.java
  src/main/java/chalmers/pimp/model/color/colormodel/ColorModelFactory.java
  src/main/java/chalmers/pimp/model/tools/DoodleTool.java
  src/main/java/chalmers/pimp/model/tools/ITool.java
  src/main/java/chalmers/pimp/model/tools/MoveTool.java
  src/main/java/chalmers/pimp/model/tools/RotateTool.java
  src/main/java/chalmers/pimp/model/tools/ShapeTool.java
  src/main/java/chalmers/pimp/model/tools/ToolFactory.java
  src/main/java/chalmers/pimp/service/FileService.java
  src/main/java/chalmers/pimp/service/ImageExportService.java
  src/main/java/chalmers/pimp/service/LayerImageService.java
  src/main/java/chalmers/pimp/util/FileUtils.java
  src/main/java/chalmers/pimp/view/GraphicsHandler.java
  src/main/java/chalmers/pimp/view/renderer/FXRenderer.java
  src/main/java/chalmers/pimp/view/renderer/SwingRenderer.java
  src/test/java/chalmers/pimp/model/ModelImplTest.java
  src/test/java/chalmers/pimp/model/PointTest.java
  src/test/java/chalmers/pimp/model/canvas/LayerManagerTest.java
  src/test/java/chalmers/pimp/model/canvas/layer/DoodleTest.java
  src/test/java/chalmers/pimp/model/color/colormodel/ColorModelMementoTest.java
  src/test/java/chalmers/pimp/model/mock/Line.java
  src/test/java/chalmers/pimp/model/mock/MouseEventMock.java
  src/test/java/chalmers/pimp/model/mock/RendererMock.java
  src/test/java/chalmers/pimp/model/tools/DoodleToolTest.java
  src/test/java/chalmers/pimp/model/tools/MoveToolTest.java
  src/test/java/chalmers/pimp/model/tools/PencilTest.java
  src/test/java/chalmers/pimp/model/tools/RotateToolTest.java
  src/test/java/chalmers/pimp/model/tools/ShapeToolTest.java
  src/test/java/chalmers/pimp/model/tools/ToolFactoryTest.java
  src/test/java/chalmers/pimp/service/ColorConverterServiceTest.java
  src/test/java/chalmers/pimp/service/ImageExportServiceTest.java
  src/test/java/chalmers/pimp/service/ImageImportServiceTest.java
  src/test/java/chalmers/pimp/service/MouseStatusCreationServiceTest.java
  src/test/java/chalmers/pimp/service/RasterDataServiceTest.java
  src/test/java/chalmers/pimp/util/AnchorPanesTest.java
  src/test/java/chalmers/pimp/util/FileUtilsTest.java
Labels: documentation, enhancement

#161 Pixel pen rotation bug
  src/main/java/chalmers/pimp/controller/components/InfoPane.java
  src/main/java/chalmers/pimp/controller/components/PimpEditorPane.java
  src/main/java/chalmers/pimp/model/IModel.java
  src/main/java/chalmers/pimp/model/LayerRotation.java
  src/main/java/chalmers/pimp/model/ModelImpl.java
  src/main/java/chalmers/pimp/model/Stroke.java
  src/main/java/chalmers/pimp/model/canvas/CanvasImpl.java
  src/main/java/chalmers/pimp/model/canvas/ICanvas.java
  src/main/java/chalmers/pimp/model/canvas/LayerManager.java
  src/main/java/chalmers/pimp/model/canvas/layer/Doodle.java
  src/main/java/chalmers/pimp/model/canvas/layer/ILayer.java
  src/main/java/chalmers/pimp/model/canvas/layer/IReadOnlyLayer.java
  src/main/java/chalmers/pimp/model/canvas/layer/LayerDelegate.java
  src/main/java/chalmers/pimp/model/canvas/layer/Raster.java
  src/main/java/chalmers/pimp/model/canvas/layer/Rectangle.java
  src/main/java/chalmers/pimp/model/command/RotateCommand.java
  src/main/java/chalmers/pimp/model/pixeldata/PixelImpl.java
  src/main/java/chalmers/pimp/model/pixeldata/RasterDataFactory.java
  src/main/java/chalmers/pimp/model/pixeldata/RasterDataImpl.java
  src/main/java/chalmers/pimp/model/tools/RasterPen.java
  src/main/java/chalmers/pimp/model/tools/ToolFactory.java
  src/main/resources/info_pane.fxml
  src/test/java/chalmers/pimp/model/tools/RasterPenTest.java
  src/test/java/chalmers/pimp/model/tools/ToolFactoryTest.java
Labels: bug

#163 Format dev
  src/main/java/chalmers/pimp/PimpApp.java
  src/main/java/chalmers/pimp/controller/IController.java
  src/main/java/chalmers/pimp/controller/components/ImageChooser.java
  src/main/java/chalmers/pimp/controller/components/InfoPane.java
  src/main/java/chalmers/pimp/controller/components/LayerItemPane.java
  src/main/java/chalmers/pimp/controller/package-info.java
  src/main/java/chalmers/pimp/model/IModel.java
  src/main/java/chalmers/pimp/model/LayerMovement.java
  src/main/java/chalmers/pimp/model/ModelImpl.java
  src/main/java/chalmers/pimp/model/Point.java
  src/main/java/chalmers/pimp/model/Stroke.java
  src/main/java/chalmers/pimp/model/canvas/layer/Doodle.java
  src/main/java/chalmers/pimp/model/canvas/layer/IColorable.java
  src/main/java/chalmers/pimp/model/canvas/layer/IDoodleLayer.java
  src/main/java/chalmers/pimp/model/canvas/layer/LayerDelegate.java
  src/main/java/chalmers/pimp/model/canvas/layer/Raster.java
  src/main/java/chalmers/pimp/model/canvas/layer/Rectangle.java
  src/main/java/chalmers/pimp/model/color/Colors.java
  src/main/java/chalmers/pimp/model/color/IColor.java
  src/main/java/chalmers/pimp/model/color/colormodel/ColorModelImpl.java
  src/main/java/chalmers/pimp/model/command/UndoRedoEvent.java
  src/main/java/chalmers/pimp/model/viewport/IViewportModel.java
  src/main/java/chalmers/pimp/model/viewport/Viewport.java
  src/main/java/chalmers/pimp/model/viewport/ViewportModelImpl.java
  src/main/java/chalmers/pimp/service/ColorConverterService.java
  src/main/java/chalmers/pimp/view/IView.java
  src/main/java/chalmers/pimp/view/ViewImpl.java
  src/main/resources/layer_pane.fxml
  src/test/java/chalmers/pimp/model/ModelImplTest.java
  src/test/java/chalmers/pimp/model/ModelMementoTest.java
  src/test/java/chalmers/pimp/model/canvas/layer/DoodleTest.java
  src/test/java/chalmers/pimp/model/canvas/layer/RectangleTest.java
  src/test/java/chalmers/pimp/model/tools/RasterPenTest.java
  src/test/java/chalmers/pimp/model/tools/ToolFactoryTest.java
Labels: enhancement
